apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-getter-app
  namespace: go-app
  labels:
    app: go-getter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-getter-app
  template:
    metadata:
      labels:
        app: go-getter-app
    spec:
      serviceAccountName: go-app-vault-auth-sa
      containers:
        - name: go-getter-app
          image: ghcr.io/govindkailas/go-getter-app:main
          imagePullPolicy: Always
          env:
            - name: VAULT_ADDR
              value: 'http://vault.vault:8200'
            - name: JWT_PATH
              value: '/var/run/secrets/kubernetes.io/serviceaccount/token'
            - name: SERVICE_PORT
              value: '8080'
            - name: SECRET_PATH
              value: 'go-app/data/user01'
            - name: APPROLE
              value: go-app-role  
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: go-app
spec:
  selector:
    app: go-getter-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort # Can be changed to LB or ClusterIP based on your need